export type ArticleType = {
  penulis: string;
  tanggal: string;
  judul: string;
  "paragraf_1_1": string;
  "paragraf_1_2": string;
  "paragraf_2_1": string;
  "paragraf_2_2": string;
  subjudul: string;
  "paragraf_3_1": string;
  "paragraf_3_2": string;
  "paragraf_3_3": string;
  kutipan_1: string;
  kutipan_2: string;
  kategori: string;
  tags: string[];
  sumber: string;
  lokasi: string;
  waktu_publikasi: string;
  referensi: string[];
  lama_baca: string;
  jumlah_kata: number;
  bahasa: string;
};
